### ISSUE TITLE
Why is StatefulSet used for a controller? How to provide high availability?

### ISSUE THREAD

**Issue by identw** [hetznercloud/csi-driver#103]
Can I put 3 replicas in statefulset hcloud-csi-controller? Will it work correctly?

**Comment by identw** [comment]
There are two additional containers inside the csi controller pod (`quay.io/k8scsi/csi-attacher` and `quay.io/k8scsi/csi-provisioner`) . It support the election . I just added options:
for quay.io/k8scsi/csi-attacher `--leader-election` and `--leader-election-type=leases`,
for  `quay.io/k8scsi/csi-provisioner` `--enable-leader-election` and `--leader-election-type=leases`.

Example:
```
...
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v1.1.1
          args:
            - --csi-address=/var/lib/csi/sockets/pluginproxy/csi.sock
            - --v=5
            - --leader-election
            - --leader-election-type=leases
...
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.2.1
          args:
            - --provisioner=csi.hetzner.cloud
            - --csi-address=/var/lib/csi/sockets/pluginproxy/csi.sock
            - --feature-gates=Topology=true
            - --v=5
            - --enable-leader-election
            - --leader-election-type=leases
...
```
Add rights to RBAC:
```
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get","create", "list", "update"]
```

Set replicas to 3. 

And it seems to work correctly for me.  Can add these options to the default deploy? Or write about them in README?
