### ISSUE TITLE
Volume attached to a node outside of kubernetes cluster

### ISSUE THREAD

**Issue by seimic** [hetznercloud/csi-driver#107]
Hi,

maybe I miss some settings but how to force the driver to attach volumes to specific nodes?

I have had now a very confusing result in following setup (simplified example here):

- In hcloud there are 7 nodes with following names (edge, n01, n02, n03, n04, n05, n06).
- Kubernetes uses only the n01-n06 nodes. Edge is outside of kubernetes and the only hcloud node with active public interface. All others are using local networking and are registered with their local IPs only.
- Nodes n01-n03 have additional taints and annotations in kubernetes to prevent pods/deployments to be scheduled on them
- In the csi-driver deployment this taints and annotations are used to deploy the driver only on this 3 nodes

```
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
	  nodeSelectorTerms:
	  - matchExpressions:
	    - key: node-role.example.com/data
          operator: In
		  values: 
		    - "true"
tolerations:
  - key: "node-role.example.com/data"
    operator: "Equal"
    value: "true"
    effect: NoSchedule
```
Result of creating a volume (mariadb helm chart with the hcloudvolume class) is - the volume is attached to the "edge" server which is not part of the kubernetes clusters. Its not accessible.

I was expecting it to create and attach the volumes to the hcloud-csi-nodes, where the driver is installed (n01-n03). 

I try to dedicate few nodes to storage and collocate database on it. Only the database should run at those nodes without any other pods/deployments.

Is this somehow possible?

Kind regards,
Michael
