### ISSUE TITLE
Add labels to the metrics services so they can easily be selected for scraping

### ISSUE THREAD

**Issue by toabi** [hetznercloud/csi-driver#125]
It would be very useful to have the services labelled so can can easily be used as a target for prometheus-operator [ServiceMonitorSpec](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#servicemonitorspec).

I don't know what the best label would be but I just tested it on our cluster with `k8s-app:hcloud-csi-node` and tried it with this `ServiceMonitor`:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hetzner-csi-node-metrics
  namespace: cattle-prometheus
spec:
  endpoints:
    - path: /
      scheme: HTTP
      targetPort: 9189
  namespaceSelector:
    matchNames: ["kube-system"]
  selector:
    matchLabels:
      k8s-app: hcloud-csi-node
```

The same would be relevant for the service `hcloud-csi-controller-metrics`.
