### ISSUE TITLE
Specification of filesystem type and retain policy

### ISSUE THREAD

**Issue by bsimpson888** [hetznercloud/csi-driver#134]
Hello together, 
Is there a way to specify the filesystem type for a volume to be created ? I would like to create a xfs volume instead of a ext4. 
Maybe this is possible through annotations, but unfortunatly I did not find any documentation about this ? 

The other question I got, is about the retain policy.  Is there a easy way to get a volume which has the retain policy set to reuse ?

Thank you in advance. 
Marco

P.S.  I never asked a question about a project in github. Is creating an issue the right way to do that, since I don't report a bug ?

**Comment by jekakm** [comment]
I'm not tested this, but try to create custom StorageClass:
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hcloud-volumes-xfs
provisioner: csi.hetzner.cloud
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  fsType: xfs
```

And use this in pvc:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: hcloud-volumes-xfs
```

May be it will be work. Please note, that all required packages (e.g. xfsprogs) must be installed on nodes
