### ISSUE TITLE
Failed to provision volume. Invalid argument capability at index 0 is not supported

### ISSUE THREAD

**Issue by grizzo-fsm** [hetznercloud/csi-driver#145]
While deploying the bitnami/wordpress helm chart, an error occurs with the generated PVC:

```Yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-wordpress
  labels:
    app.kubernetes.io/name: wordpress
    helm.sh/chart: wordpress-9.5.4
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: test
    meta.helm.sh/release-namespace: test-deployment
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "25Gi"
  storageClassName: hcloud-volumes
```

Error Message: `failed to provision volume with StorageClass "hcloud-volumes": rpc error: code = InvalidArgument desc = capability at index 0 is not supported`

I understand that the interface is not supporting the capability field at index 0 but I don't know where to check for this field, so that I can change that. Is it the StorageClass definition or the PVC? In neither of those I can find any field that would correspond to a capability field.

Any help would be appreciated.
