### ISSUE TITLE
Reuse existing Hetzner Cloud Volume

### ISSUE THREAD

**Issue by Dids** [hetznercloud/csi-driver#146]
Is it possible to reuse an existing Hetzner Cloud Volume?

Every new PVC creates a random/unique name/identifier, which is not based on the volume or PVC name, so in some cases I end up with duplicate volumes on Hetzner's side, which I then have to clean up manually.

This made me wonder if there's a name, identifier or annotation that I could utilize to ensure that the Persistent Volume name is set to a specific name every time, and whether the CSI driver would pick up on that, connecting the Hetzner Cloud Volume with the Kubernetes volume/volume claim?

**Comment by nazarkulyk** [comment]
Just specify PV with 

```yaml
csi:
    volumeHandle: "xxxxx"
    driver: csi.hetzner.cloud
    fsType: ext4
```

in you spec:

**Comment by Dids** [comment]
Thanks! While that sounds like it would indeed do what I want, it unfortunately sounds like wouldn't fit well into the infrastructure automation, eg. when the volume is first created/provisioned I would have to manually keep track of the volume handle/ID.

Unless the CSI driver syncs all Hetzner Cloud Volumes to Kubernetes as PVs, meaning I could automate the HCloud Volume part of it _before_ creating the Kubernetes cluster, then using the name/ID of that?

**Comment by Dids** [comment]
Never mind, this did indeed work exactly as described! I simply created the Hetzner Cloud Volume in Terraform first, then passed the ID to the PV's volumeHandle, which worked perfectly.

**Comment by tobias-neubert** [comment]
I am sorry. Do you have a complete example for a pv definition with a given volumeHandle? I am new to kubernetes and I don't get it done.

- Do I have to create the volume in the hetzner cloud before I create the PC/PVC? And if so, do I have to attach thee volume to a hetzner server?
- And how exactly does a pv and pvc resourcee looks like with the snippet you pasted above?

I am thankful for any help,
Tobias

**Comment by tobias-neubert** [comment]
Ok, I found my mistake. The volumeHandle must be its ID and not its name. It is bound now to my pod.

**Comment by sbaildon** [comment]
For anyone landing here looking for an example to reference an existing hcloud volume

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  storageClassName: hcloud-volumes
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  csi:
    fsType: ext4
    driver: csi.hetzner.cloud
    volumeHandle: "12345678"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: example-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: example-pv
```
