### ISSUE TITLE
MountVolume.MountDevice failed for volume with Microk8s cluster.

### ISSUE THREAD

**Issue by antosubash** [hetznercloud/csi-driver#169]
Kubernetes Version: v1.19

I'm following the example and the volume is created on the correct node and attached. but the mount fails.

```
Unable to attach or mount volumes: unmounted volumes=[my-csi-volume], unattached volumes=[default-token-wmxdx my-csi-volume]: timed out waiting for the condition
```

```
MountVolume.MountDevice failed for volume "pvc-9771b716-9b13-4da5-8c5c-99fa5173f8b0" : rpc error: code = Internal desc = failed to stage volume: mkdir /var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-9771b716-9b13-4da5-8c5c-99fa5173f8b0/globalmount: no such file or directory
```

here is the my-csi-app.yaml

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hcloud-volumes
---
kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: my-csi-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-csi-volume
      persistentVolumeClaim:
        claimName: csi-pvc
```

not sure what is the problem.
