### ISSUE TITLE
volume driver tries to run fs-resize in blockmode

### ISSUE THREAD

**Issue by SISheogorath** [hetznercloud/csi-driver#208]
Yesterday I tried to expand a device using the new blockmode. Since it was holding a LUKS blob, FS resize had a hard time and failed, rendering the entire device unusable.

Either I'm understanding something fundamentally wrong, or PVs in block mode, shouldn't try to run an FS resize after resizing the volume itself.

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myvolume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
  storageClassName: hcloud-volumes
  volumeMode: Block
```
