### ISSUE TITLE
Introduce a limit of maximum PVs per node in the CSI driver, as Hetzner cloud has that limit on the VMs

### ISSUE THREAD

**Issue by mvukadinoff** [hetznercloud/csi-driver#240]
Hello,
We ran into this issue with our Kubernetes cluster running in Hetzner and utilizing the storage driver. When we reach 16 volumes per node all subsequent attachments will fail. There is a hard limit imposed by Hetzner cloud on max 16 volumes per machine.
https://docs.hetzner.com/cloud/volumes/faq
"You can mount up to 16 volumes on each of your Hetzner Cloud servers."

Is there a way to configure the CSI driver? If not, could you introduce a configurable limit of maximum PVs per node, as Hetzner cloud has that limit on the VMs?
We believe this will be the best way to handle this if the CSI is imposing some constraints that the scheduler needs to follow, that way the scheduler should be able to find a node with less than 16 attachments. It's recommended by original design and implemented in other CSI drivers:
 https://kubernetes.io/docs/concepts/storage/storage-limits/

"If a CSI storage driver advertises a maximum number of volumes for a Node (using NodeGetInfo), the kube-scheduler honors that limit. Refer to the CSI specifications for details."

Versions:
```
quay.io/k8scsi/csi-attacher:v2.2.0
quay.io/k8scsi/csi-provisioner:v1.6.0
quay.io/k8scsi/csi-resizer:v0.3.0
hetznercloud/hcloud-csi-driver:1.5.1
```

PVC error:
```
rpc error: code = Internal desc = failed to stage volume: format of disk "/dev/disk/by-id/scsi-0HC_Volume_1xxxxxxx" failed: type:("ext4") target:("/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-034c0523-3ec7-4b06-b6a7-44ba55c722a9/globalmount") options:("defaults") errcode:(exit status 1) output:(mke2fs 1.45.6 (20-Mar-2020)
The file /dev/disk/by-id/scsi-0HC_Volume_1xxxxxdoes not exist and no size was specified.
```

Attacher error log:
```
I0402 12:23:14.715638       1 csi_handler.go:689] Found NodeID 663xxxx8 in CSINode xxxxx-k8s-node08
I0402 12:23:14.715673       1 csi_handler.go:289] VA finalizer is already set on "csi-0ea48a2b23ef3d46749775d29bb7ef0589d4119ef5c74fa08a7dda419836886d"
I0402 12:23:14.715689       1 csi_handler.go:303] NodeID annotation is already set on "csi-0ea48a2b23ef3d46749775d29bb7ef0589d4119ef5c74fa08a7dda419836886d"
I0402 12:23:14.715721       1 connection.go:182] GRPC call: /csi.v1.Controller/ControllerPublishVolume
I0402 12:23:14.715733       1 connection.go:183] GRPC request: {"node_id":"66xxxxx","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"storage.kubernetes.io/csiProvisionerIdentity":"161xxxxx8081-csi.hetzner.cloud"},"volume_id":"104xxxxx"}
I0402 12:23:15.492267       1 connection.go:185] GRPC response: {}
I0402 12:23:15.493648       1 connection.go:186] GRPC error: rpc error: code = Internal desc = failed to publish volume: maximum number of volumes already attached to the server (resource_limit_exceeded)
I0402 12:23:15.493699       1 csi_handler.go:559] Saving attach error to "csi-0ea48a2b23ef3d46749775d29bb7ef0589d4119ef5c74fa08a7dda419836886d"

```

CSI node log: (hcloud-csi-node, container : hcloud-csi-driver )
```
etes.io/csi/pv/pvc-0xxxxxx3-3ec7-4b06-b6a7-44ba55c722a9/globalmount\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:\"storage.kubernetes.io/csiProvisionerIdentity\" value:\"1xxxxxxxx-8081-csi.hetzner.cloud\" > "
level=debug ts=2021-04-01T10:32:07.596820807Z component=linux-mount-service msg="staging volume" volume-name=pvc-xxxxxxxx-3ec7-4b06-b6a7-44ba55c722a9 staging-target-path=/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-0xxxxxxx-3ec7-4b06-b6a7-44ba55c722a9/globalmount fs-type=ext4
I0401 10:32:07.597680       1 mount_linux.go:366] Disk "/dev/disk/by-id/scsi-0HC_Volume_10xxxxxxx" appears to be unformatted, attempting to format as type: "ext4" with options: [-F -m0 /dev/disk/by-id/scsi-0HC_Volume_10xxxxxx]
E0401 10:32:07.598949       1 mount_linux.go:372] format of disk "/dev/disk/by-id/scsi-0HC_Volume_10xxxxxx" failed: type:("ext4") target:("/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-xxxxxxx-3ec7-4b06-b6a7-44ba55c722a9/globalmount") options:("defaults") errcode:(exit status 1) output:(mke2fs 1.45.6 (20-Mar-2020)
The file /dev/disk/by-id/scsi-0HC_Volume_xxxxxxxx0 does not exist and no size was specified.
) 
level=error ts=2021-04-01T10:32:07.598998833Z component=grpc-server msg="handler failed" err="rpc error: code = Internal desc = failed to stage volume: format of disk \"/dev/disk/by-id/scsi-0HC_Volume_xxxxx0\" failed: type:(\"ext4\") target:(\"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-03xxxxxx-3ec7-4b06-b6a7-44ba55c722a9/globalmount\") options:(\"defaults\") errcode:(exit status 1) output:(mke2fs 1.45.6 (20-Mar-2020)\nThe file /dev/disk/by-id/scsi-0HC_Volume_1xxxxx0 does not exist and no size was specified.\n) "

```

Count of volumes:
```
node08:~# ls -la /dev/disk/by-id/ | grep Vol | wc -l
16
````

Hetzner support answered:
"Unfortunately this is a hard limit which cannot be increased."

Here is what is stated in the official Kubernets documentation:

"If a CSI storage driver advertises a maximum number of volumes for a Node (using NodeGetInfo), the kube-scheduler honors that limit. Refer to the CSI specifications for details."

https://kubernetes.io/docs/concepts/storage/storage-limits/
https://github.com/container-storage-interface/spec/blob/master/spec.md#nodegetinfo

P.S. We're reopening this issue, as the original one got closed automatically:
https://github.com/hetznercloud/csi-driver/issues/197

**Comment by LKaemmerling** [comment]
Hey @mvukadinoff,

we already set this limit since the beginning: https://github.com/hetznercloud/csi-driver/blob/master/driver/node.go#L280  It was never changed.

**Comment by mvukadinoff** [comment]
Thanks for looking, but it seems like it's not considered during scheduling, otherwise it would have chosen another node, right and not fail with:

I0402 12:23:15.493648       1 connection.go:186] GRPC error: rpc error: code = Internal desc = failed to publish volume: maximum number of volumes already attached to the server (resource_limit_exceeded

and deployment fails with: 

rpc error: code = Internal desc = failed to stage volume: format of disk "/dev/disk/by-id/scsi-0HC_Volume_1xxxxxxx" failed: type:("ext4") target:("/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-034c0523-3ec7-4b06-b6a7-44ba55c722a9/globalmount") options:("defaults") errcode:(exit status 1) output:(mke2fs 1.45.6 (20-Mar-2020)
The file /dev/disk/by-id/scsi-0HC_Volume_1xxxxxdoes not exist and no size was specified.

Which leads me to believe the pvc mount is getting pointed to a node and only then failed on the provisioner with "maximum number of volumes already attached to the server (resource_limit_exceeded"

Is it really passing it to the K8s scheduler  as specified in the CSI specifications ?

**Comment by fhofherr** [comment]
I cannot reproduce this using a single node k3s cluster, version 1.6.0
of the csi-driver, and the following configurations:

1. Create 17 PVCs and mounting them all to a single pod the output of
   `kubectl describe pod my-csi-app` is:

    ```
   Events:
   Type     Reason            Age   From               Message
    ----     ------            ----  ----               -------
    Warning  FailedScheduling  30s   default-scheduler  0/1 nodes are available: 1 node(s) exceed max volume count.
    ```

    This was the manifest I used:

    ```yaml
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: csi-pvc-1
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: hcloud-volumes
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: csi-pvc-2
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: hcloud-volumes
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: csi-pvc-3
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: hcloud-volumes
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: csi-pvc-4
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: hcloud-volumes
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: csi-pvc-5
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: hcloud-volumes
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: csi-pvc-6
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: hcloud-volumes
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: csi-pvc-7
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: hcloud-volumes
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: csi-pvc-8
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: hcloud-volumes
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: csi-pvc-9
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: hcloud-volumes
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: csi-pvc-10
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: hcloud-volumes
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: csi-pvc-11
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: hcloud-volumes
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: csi-pvc-12
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: hcloud-volumes
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: csi-pvc-13
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: hcloud-volumes
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: csi-pvc-14
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: hcloud-volumes
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: csi-pvc-15
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: hcloud-volumes
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: csi-pvc-16
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: hcloud-volumes
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: csi-pvc-17
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: hcloud-volumes
    ---
    kind: Pod
    apiVersion: v1
    metadata:
      name: my-csi-app
    spec:
      containers:
        - name: my-frontend
          image: k8s.gcr.io/pause:3.2
          volumeMounts:
          - mountPath: "/data1"
            name: vol1
          - mountPath: "/data2"
            name: vol2
          - mountPath: "/data3"
            name: vol3
          - mountPath: "/data4"
            name: vol4
          - mountPath: "/data5"
            name: vol5
          - mountPath: "/data6"
            name: vol6
          - mountPath: "/data7"
            name: vol7
          - mountPath: "/data8"
            name: vol8
          - mountPath: "/data9"
            name: vol9
          - mountPath: "/data10"
            name: vol10
          - mountPath: "/data11"
            name: vol11
          - mountPath: "/data12"
            name: vol12
          - mountPath: "/data13"
            name: vol13
          - mountPath: "/data14"
            name: vol14
          - mountPath: "/data15"
            name: vol15
          - mountPath: "/data16"
            name: vol16
          - mountPath: "/data17"
            name: vol17
      volumes:
        - name: vol1
          persistentVolumeClaim:
            claimName: csi-pvc-1
        - name: vol2
          persistentVolumeClaim:
            claimName: csi-pvc-2
        - name: vol3
          persistentVolumeClaim:
            claimName: csi-pvc-3
        - name: vol4
          persistentVolumeClaim:
            claimName: csi-pvc-4
        - name: vol5
          persistentVolumeClaim:
            claimName: csi-pvc-5
        - name: vol6
          persistentVolumeClaim:
            claimName: csi-pvc-6
        - name: vol7
          persistentVolumeClaim:
            claimName: csi-pvc-7
        - name: vol8
          persistentVolumeClaim:
            claimName: csi-pvc-8
        - name: vol9
          persistentVolumeClaim:
            claimName: csi-pvc-9
        - name: vol10
          persistentVolumeClaim:
            claimName: csi-pvc-10
        - name: vol11
          persistentVolumeClaim:
            claimName: csi-pvc-11
        - name: vol12
          persistentVolumeClaim:
            claimName: csi-pvc-12
        - name: vol13
          persistentVolumeClaim:
            claimName: csi-pvc-13
        - name: vol14
          persistentVolumeClaim:
            claimName: csi-pvc-14
        - name: vol15
          persistentVolumeClaim:
            claimName: csi-pvc-15
        - name: vol16
          persistentVolumeClaim:
            claimName: csi-pvc-16
        - name: vol17
          persistentVolumeClaim:
            claimName: csi-pvc-17
    ```

2. Create 17 PVCs and mount them to 17 Pods. This succeeded for the
   first 16 pods. The output of `kubectl describe pod` for the 17th pod
   was:

   ```
   Events:
   Type     Reason            Age    From               Message
   ----     ------            ----   ----               -------
   Warning  FailedScheduling  8m44s  default-scheduler  0/1 nodes are available: 1 node(s) exceed max volume count.
   Warning  FailedScheduling  7m27s  default-scheduler  0/1 nodes are available: 1 node(s) exceed max volume count.
   ```

   Which is also what would be expected. Note that creating the other 16
   pods took some time due to the server being locked in the backend
   while a volume was attached.

   For completenes this is the manifest I used:

   ```
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: csi-pvc-1
   spec:
     accessModes:
     - ReadWriteOnce
     resources:
       requests:
         storage: 10Gi
     storageClassName: hcloud-volumes
   ---
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: csi-pvc-2
   spec:
     accessModes:
     - ReadWriteOnce
     resources:
       requests:
         storage: 10Gi
     storageClassName: hcloud-volumes
   ---
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: csi-pvc-3
   spec:
     accessModes:
     - ReadWriteOnce
     resources:
       requests:
         storage: 10Gi
     storageClassName: hcloud-volumes
   ---
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: csi-pvc-4
   spec:
     accessModes:
     - ReadWriteOnce
     resources:
       requests:
         storage: 10Gi
     storageClassName: hcloud-volumes
   ---
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: csi-pvc-5
   spec:
     accessModes:
     - ReadWriteOnce
     resources:
       requests:
         storage: 10Gi
     storageClassName: hcloud-volumes
   ---
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: csi-pvc-6
   spec:
     accessModes:
     - ReadWriteOnce
     resources:
       requests:
         storage: 10Gi
     storageClassName: hcloud-volumes
   ---
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: csi-pvc-7
   spec:
     accessModes:
     - ReadWriteOnce
     resources:
       requests:
         storage: 10Gi
     storageClassName: hcloud-volumes
   ---
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: csi-pvc-8
   spec:
     accessModes:
     - ReadWriteOnce
     resources:
       requests:
         storage: 10Gi
     storageClassName: hcloud-volumes
   ---
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: csi-pvc-9
   spec:
     accessModes:
     - ReadWriteOnce
     resources:
       requests:
         storage: 10Gi
     storageClassName: hcloud-volumes
   ---
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: csi-pvc-10
   spec:
     accessModes:
     - ReadWriteOnce
     resources:
       requests:
         storage: 10Gi
     storageClassName: hcloud-volumes
   ---
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: csi-pvc-11
   spec:
     accessModes:
     - ReadWriteOnce
     resources:
       requests:
         storage: 10Gi
     storageClassName: hcloud-volumes
   ---
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: csi-pvc-12
   spec:
     accessModes:
     - ReadWriteOnce
     resources:
       requests:
         storage: 10Gi
     storageClassName: hcloud-volumes
   ---
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: csi-pvc-13
   spec:
     accessModes:
     - ReadWriteOnce
     resources:
       requests:
         storage: 10Gi
     storageClassName: hcloud-volumes
   ---
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: csi-pvc-14
   spec:
     accessModes:
     - ReadWriteOnce
     resources:
       requests:
         storage: 10Gi
     storageClassName: hcloud-volumes
   ---
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: csi-pvc-15
   spec:
     accessModes:
     - ReadWriteOnce
     resources:
       requests:
         storage: 10Gi
     storageClassName: hcloud-volumes
   ---
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: csi-pvc-16
   spec:
     accessModes:
     - ReadWriteOnce
     resources:
       requests:
         storage: 10Gi
     storageClassName: hcloud-volumes
   ---
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: csi-pvc-17
   spec:
     accessModes:
     - ReadWriteOnce
     resources:
       requests:
         storage: 10Gi
     storageClassName: hcloud-volumes
   ---
   kind: Pod
   apiVersion: v1
   metadata:
     name: my-csi-app-1
   spec:
     containers:
       - name: my-frontend
         image: k8s.gcr.io/pause:3.2
         volumeMounts:
         - mountPath: "/data1"
           name: vol1
     volumes:
       - name: vol1
         persistentVolumeClaim:
           claimName: csi-pvc-1
   ---
   kind: Pod
   apiVersion: v1
   metadata:
     name: my-csi-app-1
   spec:
     containers:
       - name: my-frontend
         image: k8s.gcr.io/pause:3.2
         volumeMounts:
         - mountPath: "/data1"
           name: vol1
     volumes:
       - name: vol1
         persistentVolumeClaim:
           claimName: csi-pvc-1
   ---
   kind: Pod
   apiVersion: v1
   metadata:
     name: my-csi-app-2
   spec:
     containers:
       - name: my-frontend
         image: k8s.gcr.io/pause:3.2
         volumeMounts:
         - mountPath: "/data2"
           name: vol2
     volumes:
       - name: vol2
         persistentVolumeClaim:
           claimName: csi-pvc-2
   ---
   kind: Pod
   apiVersion: v1
   metadata:
     name: my-csi-app-3
   spec:
     containers:
       - name: my-frontend
         image: k8s.gcr.io/pause:3.2
         volumeMounts:
         - mountPath: "/data3"
           name: vol3
     volumes:
       - name: vol3
         persistentVolumeClaim:
           claimName: csi-pvc-3
   ---
   kind: Pod
   apiVersion: v1
   metadata:
     name: my-csi-app-4
   spec:
     containers:
       - name: my-frontend
         image: k8s.gcr.io/pause:3.2
         volumeMounts:
         - mountPath: "/data4"
           name: vol4
     volumes:
       - name: vol4
         persistentVolumeClaim:
           claimName: csi-pvc-4
   ---
   kind: Pod
   apiVersion: v1
   metadata:
     name: my-csi-app-5
   spec:
     containers:
       - name: my-frontend
         image: k8s.gcr.io/pause:3.2
         volumeMounts:
         - mountPath: "/data5"
           name: vol5
     volumes:
       - name: vol5
         persistentVolumeClaim:
           claimName: csi-pvc-5
   ---
   kind: Pod
   apiVersion: v1
   metadata:
     name: my-csi-app-6
   spec:
     containers:
       - name: my-frontend
         image: k8s.gcr.io/pause:3.2
         volumeMounts:
         - mountPath: "/data6"
           name: vol6
     volumes:
       - name: vol6
         persistentVolumeClaim:
           claimName: csi-pvc-6
   ---
   kind: Pod
   apiVersion: v1
   metadata:
     name: my-csi-app-7
   spec:
     containers:
       - name: my-frontend
         image: k8s.gcr.io/pause:3.2
         volumeMounts:
         - mountPath: "/data7"
           name: vol7
     volumes:
       - name: vol7
         persistentVolumeClaim:
           claimName: csi-pvc-7
   ---
   kind: Pod
   apiVersion: v1
   metadata:
     name: my-csi-app-8
   spec:
     containers:
       - name: my-frontend
         image: k8s.gcr.io/pause:3.2
         volumeMounts:
         - mountPath: "/data8"
           name: vol8
     volumes:
       - name: vol8
         persistentVolumeClaim:
           claimName: csi-pvc-8
   ---
   kind: Pod
   apiVersion: v1
   metadata:
     name: my-csi-app-9
   spec:
     containers:
       - name: my-frontend
         image: k8s.gcr.io/pause:3.2
         volumeMounts:
         - mountPath: "/data9"
           name: vol9
     volumes:
       - name: vol9
         persistentVolumeClaim:
           claimName: csi-pvc-9
   ---
   kind: Pod
   apiVersion: v1
   metadata:
     name: my-csi-app-10
   spec:
     containers:
       - name: my-frontend
         image: k8s.gcr.io/pause:3.2
         volumeMounts:
         - mountPath: "/data10"
           name: vol10
     volumes:
       - name: vol10
         persistentVolumeClaim:
           claimName: csi-pvc-10
   ---
   kind: Pod
   apiVersion: v1
   metadata:
     name: my-csi-app-11
   spec:
     containers:
       - name: my-frontend
         image: k8s.gcr.io/pause:3.2
         volumeMounts:
         - mountPath: "/data11"
           name: vol11
     volumes:
       - name: vol11
         persistentVolumeClaim:
           claimName: csi-pvc-11
   ---
   kind: Pod
   apiVersion: v1
   metadata:
     name: my-csi-app-12
   spec:
     containers:
       - name: my-frontend
         image: k8s.gcr.io/pause:3.2
         volumeMounts:
         - mountPath: "/data12"
           name: vol12
     volumes:
       - name: vol12
         persistentVolumeClaim:
           claimName: csi-pvc-12
   ---
   kind: Pod
   apiVersion: v1
   metadata:
     name: my-csi-app-13
   spec:
     containers:
       - name: my-frontend
         image: k8s.gcr.io/pause:3.2
         volumeMounts:
         - mountPath: "/data13"
           name: vol13
     volumes:
       - name: vol13
         persistentVolumeClaim:
           claimName: csi-pvc-13
   ---
   kind: Pod
   apiVersion: v1
   metadata:
     name: my-csi-app-14
   spec:
     containers:
       - name: my-frontend
         image: k8s.gcr.io/pause:3.2
         volumeMounts:
         - mountPath: "/data14"
           name: vol14
     volumes:
       - name: vol14
         persistentVolumeClaim:
           claimName: csi-pvc-14
   ---
   kind: Pod
   apiVersion: v1
   metadata:
     name: my-csi-app-15
   spec:
     containers:
       - name: my-frontend
         image: k8s.gcr.io/pause:3.2
         volumeMounts:
         - mountPath: "/data15"
           name: vol15
     volumes:
       - name: vol15
         persistentVolumeClaim:
           claimName: csi-pvc-15
   ---
   kind: Pod
   apiVersion: v1
   metadata:
     name: my-csi-app-16
   spec:
     containers:
       - name: my-frontend
         image: k8s.gcr.io/pause:3.2
         volumeMounts:
         - mountPath: "/data16"
           name: vol16
     volumes:
       - name: vol16
         persistentVolumeClaim:
           claimName: csi-pvc-16
   ---
   kind: Pod
   apiVersion: v1
   metadata:
     name: my-csi-app-17
   spec:
     containers:
       - name: my-frontend
         image: k8s.gcr.io/pause:3.2
         volumeMounts:
         - mountPath: "/data17"
           name: vol17
     volumes:
       - name: vol17
         persistentVolumeClaim:
           claimName: csi-pvc-17
   ```

The only way I could reproduce the issue was by manually attaching
volumes to the server before creating PVCs and mounting them to pods.
The csi driver does not query the API for volumes currently attached,
but rather seems to keep track of that number itself. Therefore manually
attaching a volume trips it up.

The [`NodeGetInfo`](https://github.com/container-storage-interface/spec/blob/master/spec.md#nodegetinfo) call does not allow to pass the current number of volumes attached to the node. Nor can implementors expect that `NodeGetInfo` is called more than once. This makes it impossible to pass any information regarding the amount of currently attached volumes.

There **may** be the possibility to support this case if the Hetzner csi-driver would implement [`ListVolumes`](https://github.com/container-storage-interface/spec/blob/master/spec.md#listvolumes), which it currently does not. Nor does it advertise the `LIST_VOLUMES` capability. For the time being I am not able to give an ETA when or if we are going to implement the `LIST_VOLUMES` capability. However, I created issue number #258 to keep track of that.
