### ISSUE TITLE
Node silently powers off when attaching many volumes

### ISSUE THREAD

**Issue by sjagoe** [hetznercloud/csi-driver#241]
#### Problem

When kubernetes schedules multiple pods (close to 16) with persistent storage to a single node:
- Initially pods start correctly
- Some volume attachments fail with `server is locked` (expected)
- Some volume attachments fail with `timed out waiting for condition` (expected, sort of) 
- Before all volumes are attached, `unknown_error` occurs (see kube event below) and node silently powers off

It also seems to occur once per node; once a node has failed in this way I have not been able to cause another failure. Deleting and re-running the workload a second time does eventually succeed. Unfortunately just rebooting a node before testing it in this way does not prevent the issue from occurring.

Script to create 16 pvcs and pods is at the bottom of this report.

We initially ran into this issue on v1.5.3, but it also occurs after upgrade to v1.6.0

```
$ kubectl get event --watch
LAST SEEN   TYPE      REASON                   OBJECT                             MESSAGE
33m         Normal    WaitForFirstConsumer     persistentvolumeclaim/csi-pvc-1    waiting for first consumer to be created before binding
33m         Normal    ExternalProvisioning     persistentvolumeclaim/csi-pvc-1    waiting for a volume to be created, either by external provisioner "csi.hetzner.cloud" o
r manually created by system administrator
33m         Normal    Provisioning             persistentvolumeclaim/csi-pvc-1    External provisioner is provisioning volume for claim "simon-smartly-v1/csi-pvc-1"
33m         Normal    ProvisioningSucceeded    persistentvolumeclaim/csi-pvc-1    Successfully provisioned volume pvc-b803a043-325d-412c-9025-eabd255ad64b

...

33m         Normal    Scheduled                pod/csi-test-1                     Successfully assigned my-namespace/csi-test-1 to kube-cloud-node1
33m         Warning   FailedAttachVolume       pod/csi-test-1                     AttachVolume.Attach failed for volume "pvc-b803a043-325d-412c-9025-eabd255ad64b" : rpc error: code = Unavailable desc = failed to publish volume: server is locked
33m         Normal    SuccessfulAttachVolume   pod/csi-test-1                     AttachVolume.Attach succeeded for volume "pvc-b803a043-325d-412c-9025-eabd255ad64b"
32m         Normal    Pulling                  pod/csi-test-1                     Pulling image "busybox"
32m         Normal    Pulled                   pod/csi-test-1                     Successfully pulled image "busybox" in 1.8215677s
32m         Normal    Created                  pod/csi-test-1                     Created container do-nothing
32m         Normal    Started                  pod/csi-test-1                     Started container do-nothing
31m         Normal    Killing                  pod/csi-test-1                     Stopping container do-nothing
28m         Normal    Scheduled                pod/csi-test-1                     Successfully assigned my-namespace/csi-test-1 to kube-cloud-node1
27m         Warning   FailedAttachVolume       pod/csi-test-1                     AttachVolume.Attach failed for volume "pvc-10386aee-7ee0-45e0-9e42-44ec4175332d" : rpc error: code = Unavailable desc = failed to publish volume: server is locked
26m         Warning   FailedMount              pod/csi-test-1                     Unable to attach or mount volumes: unmounted volumes=[csi-1 default-token-2l4qt], unattached volumes=[csi-1 default-token-2l4qt]: timed out waiting for the condition
23m         Normal    Scheduled                pod/csi-test-1                     Successfully assigned my-namespace/csi-test-1 to kube-cloud-node1

... more like the above for each pod ...
... <eventually> ...

0s          Normal    SuccessfulAttachVolume   pod/csi-test-11                    AttachVolume.Attach succeeded for volume "pvc-3da5be71-ac40-4da3-ad24-0e3022e28608"
0s          Warning   NodeNotReady             pod/csi-test-4                     Node is not ready
0s          Warning   NodeNotReady             pod/csi-test-9                     Node is not ready
0s          Warning   NodeNotReady             pod/csi-test-5                     Node is not ready
0s          Warning   NodeNotReady             pod/csi-test-13                    Node is not ready
0s          Warning   NodeNotReady             pod/csi-test-15                    Node is not ready
0s          Warning   NodeNotReady             pod/csi-test-1                     Node is not ready
0s          Warning   NodeNotReady             pod/csi-test-2                     Node is not ready
0s          Warning   NodeNotReady             pod/csi-test-14                    Node is not ready
0s          Warning   NodeNotReady             pod/csi-test-7                     Node is not ready
0s          Warning   FailedAttachVolume       pod/csi-test-8                     AttachVolume.Attach failed for volume "pvc-46ea41c6-8911-48ec-b996-01445ff8cacd" : rpc error: code = Internal desc = failed to publish volume: Volume assigning step has failed due to an unknown error. (unknown_error)
```

#### Background

We are busy moving much of our development environment to Hetzner Cloud based kubernetes nodes so that we can use persistent volumes. During real usage of a cluster container 100 Hetzner Cloud nodes, we have run into the issue above. I was unable to directly trigger it by just calling the Hetzner Cloud API with a script, so resorted creating a minimal example with kubernetes.

#### Script to reproduce the issue

```
#!/usr/bin/env bash

TEST_NODE_NAME=kube-cloud-node1

read -r -d '' TEMPLATE <<EOF
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-REPLACE
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
  storageClassName: hcloud-volumes
---
apiVersion: v1
kind: Pod
metadata:
  name: csi-test-REPLACE
spec:
  terminationGracePeriodSeconds: 1
  nodeSelector:
    kubernetes.io/hostname: "${TEST_NODE_NAME}"
  containers:
    - image: busybox
      name: do-nothing
      command: ["/bin/sh", "-c", "sleep 900000"]
      volumeMounts:
        - mountPath: "/data"
          name: csi-REPLACE
  restartPolicy: Never
  volumes:
    - name: csi-REPLACE
      persistentVolumeClaim:
        claimName: csi-pvc-REPLACE
EOF

MANIFEST=
for volume_number in {1..16}; do
    MANIFEST="$MANIFEST"$'\n'"${TEMPLATE//-REPLACE/-${volume_number}}"
done

echo "$MANIFEST" | kubectl apply -f -
```
