### ISSUE TITLE
Please make it possible to specify a volume name (in addition to volume id) in spec/csi/volumeHandle for PV manifests

### ISSUE THREAD

**Issue by fabriziogiudici** [hetznercloud/csi-driver#250]
I've used the Hezner CSI driver with success for creating a pre-provisioned PV as explained here: https://kubernetes.io/blog/2019/01/15/container-storage-interface-ga/#pre-provisioned-volumes

Let's suppose I have a volume such as:

```
% hcloud volume list
ID         NAME             SIZE    SERVER        LOCATION
12345678   my-volume-name   10 GB   -             hel1
```

I see that the ```volumeHandle``` works with the numerical ID of the volume, as in:

```
spec:
  csi:
    driver: csi-driver.example.com
    volumeHandle: "12345678"
```

but it doesn't work trying to pass the volume name, such as:

```
spec:
  csi:
    driver: csi-driver.example.com
    volumeHandle: "my-volume-name"
```

Minor stuff, but it would be nice to allow the latter option, so in case of destroying and recreating the volume no manifest would need a change.
