### ISSUE TITLE
use hcloud as secret name to store token instead of hcloud-csi

### ISSUE THREAD

**Issue by sandromodarelli** [hetznercloud/csi-driver#254]
it would be great to change the default secret name to store hetzner token in your deployment manifest.
the best secret name can be `hcloud`, the same used into https://github.com/hetznercloud/hcloud-cloud-controller-manager.

in this way we can create a single secret in `kube-system` to store the hetzner token and apply controller manager and CSI at the same time

**Comment by fhofherr** [comment]
Hi @sandromodarelli,

thank you for your suggestion. I agree the current state somewhat unsatisfying. Unfortunately this would break things for everyone currently relying on the old secret name. We therefore cannot do this in the current 1.x release. However, we will re-consider it for a future major release. As such I will leave the issue open, but please understand that I can give no timeline when we will be able to address it.

In the mean time your best option is to modify the deplyoment we provide using [kustomize](https://kustomize.io/).

Something like this should work:

```
patches:
  - target:
      kind: StatefulSet
      name: hcloud-csi-controller
      patch: |-
          - op: replace
            path: /spec/template/spec/containers/3/env/3/valueFrom/secretKeyRef/name
            value: hcloud
```
