### ISSUE TITLE
Adding multiple volume to a pod causes "waiting for first consumer to be created before binding"

### ISSUE THREAD

**Issue by Mormoroth** [hetznercloud/csi-driver#30]
Hi, i have added to 4 volumes to a pod. and and only first two is created. The others showing `waiting for first consumer to be created before binding`, but its working fine with previous versions. The only changes i see is `volumeBindingMode: WaitForFirstConsumer` 
and `--feature-gates=Topology=true`

Here is the pod specs:

`apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hcloud-volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hcloud-volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc3
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hcloud-volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc4
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hcloud-volumes
---
kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: my-csi-volume
      - mountPath: "/data2"
        name: my-csi-volume2
      - mountPath: "/data3"
        name: my-csi-volume3
      - mountPath: "/data4"
        name: my-csi-volume4
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-csi-volume
      persistentVolumeClaim:
        claimName: csi-pvc
    - name: my-csi-volume2
      persistentVolumeClaim:
        claimName: csi-pvc2
    - name: my-csi-volume3
      persistentVolumeClaim:
        claimName: csi-pvc3
    - name: my-csi-volume4
      persistentVolumeClaim:
        claimName: csi-pvc4`

**Comment by thcyron** [comment]
I wasn’t able to reproduce this. Creating a pod with 3 different persistent volumes did work for me:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hcloud-volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hcloud-volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-3
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hcloud-volumes
---
kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data-1"
        name: my-csi-volume-1
      - mountPath: "/data-2"
        name: my-csi-volume-2
      - mountPath: "/data-3"
        name: my-csi-volume-3
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-csi-volume-1
      persistentVolumeClaim:
        claimName: csi-pvc-1
    - name: my-csi-volume-2
      persistentVolumeClaim:
        claimName: csi-pvc-2
    - name: my-csi-volume-3
      persistentVolumeClaim:
        claimName: csi-pvc-3
```

```
Volumes:
  my-csi-volume-1:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  csi-pvc-1
    ReadOnly:   false
  my-csi-volume-2:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  csi-pvc-2
    ReadOnly:   false
  my-csi-volume-3:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  csi-pvc-3
    ReadOnly:   false
```

Please verify your setup.
