### ISSUE TITLE
Feature Request: fstype

### ISSUE THREAD

**Issue by tipruzs** [hetznercloud/csi-driver#32]
Is it possible to implement fstype parameter, so we can choose the filesystem (xfs/ext4) during  provisioning?

**Comment by deacix** [comment]
I need it as well! Please implement!

**Comment by akhfa** [comment]
I just want to know why do you prefer one fstype from the others?

**Comment by tipruzs** [comment]
There are a many applications which profit from xfs for performance reasons, e.g. mongodb

**Comment by LKaemmerling** [comment]
This is already possible. You can create a new (custom) storage class with a parameter `fsType`:
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: kube-system
  name: hcloud-volumes-xfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.hetzner.cloud
volumeBindingMode: WaitForFirstConsumer
parameters:
  fsType: xfs
```

And use this storage class in your pvc:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hcloud-volumes-xfs
```
