### ISSUE TITLE
Volume Formatting breaks Block mode in v2

### ISSUE THREAD

**Issue by m4eba** [hetznercloud/csi-driver#349]
Every volume gets formatted even if in block mode.

**Comment by timbrd** [comment]
This might be the cause why I am not able to provision a rook ceph cluster anymore.
When initializing the osds, rook does not find any valid block devices:

````
provision 2022-12-23 17:34:24.432561 I cephosd: skipping device "/mnt/set1-data-1tl48r" because it contains a filesystem "ext4"
provision 2022-12-23 17:34:24.461665 I cephosd: configuring osd devices: {"Entries":{}}                                                                                        
provision 2022-12-23 17:34:24.461685 I cephosd: no new devices to configure. returning devices already configured with ceph-volume.
````

The pvc configured is in block mode:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  [...]
  name: set1-data-1tl48r
  namespace: rook-ceph
  [...]
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 90Gi
  storageClassName: hcloud-volumes
  volumeMode: Block
  volumeName: pvc-00bbd41c-548a-4d6d-a33d-05e0beba2584
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 90Gi
  phase: Bound
```
