### ISSUE TITLE
HTTP proxy for API access

### ISSUE THREAD

**Issue by bheisig** [hetznercloud/csi-driver#391]
Hello,
we've deployed a vanilla kubernetes cluster on some hcloud servers which only have private IPv4 addresses. We've also deployed an HTTP proxy on another hcloud server. Now, we'd like to use this CSI but faced an issue that the hcloud API is not reachable. Is it possible to configure the CSI to use an HTTP proxy to access the API?

**Comment by bheisig** [comment]
Thanks for the hint, @apricote. A was successfully able to implement these environment variables using kustomize:

~~~ {.yaml}
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/hetznercloud/csi-driver/deploy/kubernetes/?ref=v2.2.0
patches:
  - target:
      kind: Deployment
      name: hcloud-csi-controller
    patch: |-
      - op: add
        path: /spec/template/spec/containers/3/env
        value:
          - name: HTTP_PROXY
            value: http://http-proxy.example.com:3128
          - name: HTTPS_PROXY
            value: http://http-proxy.example.com:3128
          - name: CSI_ENDPOINT
            value: unix:///run/csi/socket
          - name: METRICS_ENDPOINT
            value: 0.0.0.0:9189
          - name: ENABLE_METRICS
            value: "true"
          - name: KUBE_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: HCLOUD_TOKEN
            valueFrom:
              secretKeyRef:
                key: token
                name: hcloud
namespace: kube-system
~~~

As you see, it has some caveats. I had to duplicate some envs from the original deployment. And I use `3` in the patch path because `hcloud-csi-driver` is the 4th container in the deployment. My knowledge of kustomize (especially JSON6902) is limited. If you have a cleaner solution I'd like to hear from you.

**Comment by apricote** [comment]
I personally find strategic merge patches easier to read and understand. They allow merging based on list names and other properties.

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/hetznercloud/csi-driver/deploy/kubernetes/?ref=v2.2.0

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: hcloud-csi-controller
        namespace: kube-system
      spec:
        template:
          spec:
            containers:
              - name: hcloud-csi-driver
                env:
                  - name: HTTP_PROXY
                    value: http://http-proxy.example.com:3128
                  - name: HTTPS_PROXY
                    value: http://http-proxy.example.com:3128
```

Mid-term you should be able to set additional environment variables through the Helm Chart #108
