### ISSUE TITLE
Reattach already created volume

### ISSUE THREAD

**Issue by loxal** [hetznercloud/csi-driver#44]
I want to reattach an already created volume and specified:

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: storage
spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: hcloud-volumes
    volumeMode: Filesystem
    **volumeName: pvc-2d1ad3c7-ffba-42ea-9987-xxxx**
```
The volumeName refers to the Volume ID that was already created. However this volume cannot be reattached. 

Any tips? @thcyron :)
