### ISSUE TITLE
Affinity missing for physical nodes

### ISSUE THREAD

**Issue by cristianrat** [hetznercloud/csi-driver#457]
Long story short, this bit
```
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: instance.hetzner.cloud/is-root-server
                operator: NotIn
                values:
                - "true"
```
Seems to be missing for the deployment controller
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcloud-csi-controller
  namespace: kube-system
```
I am running a cluster that has both cloud and metal boxes - and was having a hard time understanding why my volume mounting / unmounting stopped working, even after I had applied the label `instance.hetzner.cloud/is-root-server=true`
(version 2.3.0)
