### ISSUE TITLE
feat(helm): deploy Grafana dashboard

### ISSUE THREAD

**Issue by apricote** [hetznercloud/csi-driver#557]
We should make it possible to automatically deploy the [Grafana dashboard](https://github.com/hetznercloud/csi-driver/blob/main/deploy/monitoring/grafana-dashboard.json) through the Helm Chart. The Grafana Helm Chart includes a sidecar that watches `ConfigMaps` with the `grafana_dashboard: 1` label and imports them into the Grafana instance.

1. Add new keys to `chart/values.yaml`:
    ```yaml
    metrics:
      dashboard:
        # If enabled, deploy a ConfigMap with our Grafana dashboard.
        enabled: false
        labels:
          grafana_dashboard: 1
   ```
2. Add a new file `chart/templates/core/grafana-dashboard.yaml` that renders the ConfigMap with the dashboard as a data field if `metrics.dashboard.enabled==true`. Check if we can potentially symlink the dashboard from its current configuration or we need to create a copy.

Pointers:
- https://github.com/grafana/helm-charts/tree/main/charts/grafana#sidecar-for-dashboards
- https://helm.sh/docs/chart_template_guide/accessing_files/#configmap-and-secrets-utility-functions
