### ISSUE TITLE
CPU Usage slowly increasing

### ISSUE THREAD

**Issue by apricote** [hetznercloud/csi-driver#58]
### Summary

In our deployment the csi-driver will slowly raise its CPU usage over multiple days.

![hcloud-csi-cpu-leak](https://user-images.githubusercontent.com/3393079/65426198-079bba00-de10-11e9-9b1a-b99e0722cfa8.png)

I killed the pod on 09/17 16:00, causing the usage to "reset".

### Access Pattern

* We have a total of 5 persistent volumes created in the cluster
* 1 is unbound (no pvc)
* 2 are associated with prometheus and rarely need to be reassigned
* 2 are associated with cronjobs that run on a 5 minute schedule, requiring the volumes to be attached+mounted every 5 minutes (_I suspect this might leak some watches/internal timers that cause the growing CPU usage_)

```
➜  ~ kubectl get pvc --all-namespaces
NAMESPACE                         NAME                                                                 STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS     AGE
cattle-prometheus                 prometheus-cluster-monitoring-db-prometheus-cluster-monitoring-0     Bound    pvc-5e4ed3ef-c26d-11e9-9e15-9600002e0c70   10Gi       RWO            hcloud-volumes   35d
platform-monitoring               prometheus-platform-monitoring-db-prometheus-platform-monitoring-0   Bound    pvc-c01b6132-d8b6-11e9-9ef9-9600002e0c6f   10Gi       RWO            hcloud-volumes   6d17h
REDACTED                          REDACTED                                                             Bound    pvc-ff65820a-c1da-11e9-981f-9600002e0ca4   10Gi       RWO            hcloud-volumes   35d
REDACTED                          REDACTED-2                                                           Bound    pvc-d47da832-bda7-11e9-912b-960000172088   10Gi       RWO            hcloud-volumes   41d
➜  ~ kubectl get pv --all-namespaces 
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                                                                                    STORAGECLASS     REASON   AGE
pvc-49de8eef-adfe-11e9-912b-960000172088   10Gi       RWO            Retain           Released   cattle-prometheus/prometheus-cluster-monitoring-db-prometheus-cluster-monitoring-0       hcloud-volumes            61d
pvc-5e4ed3ef-c26d-11e9-9e15-9600002e0c70   10Gi       RWO            Delete           Bound      cattle-prometheus/prometheus-cluster-monitoring-db-prometheus-cluster-monitoring-0       hcloud-volumes            35d
pvc-c01b6132-d8b6-11e9-9ef9-9600002e0c6f   10Gi       RWO            Delete           Bound      platform-monitoring/prometheus-platform-monitoring-db-prometheus-platform-monitoring-0   hcloud-volumes            6d17h
pvc-d47da832-bda7-11e9-912b-960000172088   10Gi       RWO            Delete           Bound      REDACTED/REDACTED-2                                                                      hcloud-volumes            41d
pvc-ff65820a-c1da-11e9-981f-9600002e0ca4   10Gi       RWO            Delete           Bound      REDACTED/REDACTED                                                                        hcloud-volumes            35d
```

### Details

- CSI-Driver Version: 1.1.5
- K8s Version: 1.14.5

```
➜  ~ kubectl version  
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

<details><summary>Logs from Container <code>hcloud-csi-driver</code> directly after restart</summary>
<p>

```
level=debug ts=2019-09-23T12:34:59.042539352Z msg="getting instance id from metadata service"
level=debug ts=2019-09-23T12:34:59.048672227Z msg="fetching server"
level=info ts=2019-09-23T12:34:59.386696775Z msg="fetched server" server-name=compute4
level=debug ts=2019-09-23T12:34:59.477231815Z component=grpc-server msg="handling request" req=
level=debug ts=2019-09-23T12:34:59.477353825Z component=grpc-server msg="finished handling request"
level=debug ts=2019-09-23T12:34:59.480500769Z component=grpc-server msg="handling request" req=
level=debug ts=2019-09-23T12:34:59.480590227Z component=grpc-server msg="finished handling request"
level=debug ts=2019-09-23T12:34:59.484366757Z component=grpc-server msg="handling request" req=
level=debug ts=2019-09-23T12:34:59.484420039Z component=grpc-server msg="finished handling request"
level=debug ts=2019-09-23T12:34:59.488958315Z component=grpc-server msg="handling request" req=
level=debug ts=2019-09-23T12:34:59.489026328Z component=grpc-server msg="finished handling request"
level=debug ts=2019-09-23T12:35:00.301813104Z component=grpc-server msg="handling request" req=
level=debug ts=2019-09-23T12:35:00.301896393Z component=grpc-server msg="finished handling request"
level=debug ts=2019-09-23T12:35:00.31035102Z component=grpc-server msg="handling request" req=
level=debug ts=2019-09-23T12:35:00.310428105Z component=grpc-server msg="finished handling request"
level=debug ts=2019-09-23T12:35:00.314012584Z component=grpc-server msg="handling request" req=
level=debug ts=2019-09-23T12:35:00.314080245Z component=grpc-server msg="finished handling request"
level=debug ts=2019-09-23T12:35:00.318897099Z component=grpc-server msg="handling request" req=
level=debug ts=2019-09-23T12:35:00.318935292Z component=grpc-server msg="finished handling request"
level=debug ts=2019-09-23T12:35:08.986510143Z component=grpc-server msg="handling request" req="volume_id:\"3098265\" node_id:\"3142363\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:\"storage.kubernetes.io/csiProvisionerIdentity\" value:\"1566060975326-8081-csi.hetzner.cloud\" > "
level=info ts=2019-09-23T12:35:08.98664899Z component=api-volume-service msg="attaching volume" volume-id=3098265 server-id=3142363
level=debug ts=2019-09-23T12:35:12.282519058Z component=grpc-server msg="finished handling request"
level=debug ts=2019-09-23T12:35:35.058390576Z component=grpc-server msg="handling request" req="volume_id:\"3098265\" node_id:\"3142363\" "
level=info ts=2019-09-23T12:35:35.058546437Z component=api-volume-service msg="detaching volume from server" volume-id=3098265 server-id=3142363
level=debug ts=2019-09-23T12:35:37.349104517Z component=grpc-server msg="finished handling request"
level=debug ts=2019-09-23T12:40:01.540748703Z component=grpc-server msg="handling request" req="volume_id:\"3098265\" node_id:\"3142354\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:\"storage.kubernetes.io/csiProvisionerIdentity\" value:\"1566060975326-8081-csi.hetzner.cloud\" > "
level=info ts=2019-09-23T12:40:01.540829349Z component=api-volume-service msg="attaching volume" volume-id=3098265 server-id=3142354
level=debug ts=2019-09-23T12:40:07.529582765Z component=grpc-server msg="finished handling request"
level=debug ts=2019-09-23T12:40:07.547330301Z component=grpc-server msg="handling request" req="volume_id:\"3098265\" node_id:\"3142354\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:\"storage.kubernetes.io/csiProvisionerIdentity\" value:\"1566060975326-8081-csi.hetzner.cloud\" > "
level=info ts=2019-09-23T12:40:07.547552922Z component=api-volume-service msg="attaching volume" volume-id=3098265 server-id=3142354
level=info ts=2019-09-23T12:40:08.1849406Z component=api-volume-service msg="failed to attach volume" volume-id=3098265 server-id=3142354 err="volume is already attached to a server, please detach it first (service_error)"
level=debug ts=2019-09-23T12:40:08.225571172Z component=grpc-server msg="finished handling request"
level=debug ts=2019-09-23T12:40:27.167239085Z component=grpc-server msg="handling request" req="volume_id:\"3098265\" node_id:\"3142354\" "
level=info ts=2019-09-23T12:40:27.167581839Z component=api-volume-service msg="detaching volume from server" volume-id=3098265 server-id=3142354
level=debug ts=2019-09-23T12:40:29.483828719Z component=grpc-server msg="finished handling request"
level=debug ts=2019-09-23T12:45:03.489533212Z component=grpc-server msg="handling request" req="volume_id:\"3098265\" node_id:\"3142352\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:\"storage.kubernetes.io/csiProvisionerIdentity\" value:\"1566060975326-8081-csi.hetzner.cloud\" > "
level=info ts=2019-09-23T12:45:03.489663779Z component=api-volume-service msg="attaching volume" volume-id=3098265 server-id=3142352
level=debug ts=2019-09-23T12:45:07.818956291Z component=grpc-server msg="finished handling request"
level=debug ts=2019-09-23T12:45:34.322893995Z component=grpc-server msg="handling request" req="volume_id:\"3098265\" node_id:\"3142352\" "
level=info ts=2019-09-23T12:45:34.322972245Z component=api-volume-service msg="detaching volume from server" volume-id=3098265 server-id=3142352
level=debug ts=2019-09-23T12:45:36.618721636Z component=grpc-server msg="finished handling request"
level=debug ts=2019-09-23T12:50:05.781757496Z component=grpc-server msg="handling request" req="volume_id:\"3098265\" node_id:\"3142350\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:\"storage.kubernetes.io/csiProvisionerIdentity\" value:\"1566060975326-8081-csi.hetzner.cloud\" > "
level=info ts=2019-09-23T12:50:05.781999032Z component=api-volume-service msg="attaching volume" volume-id=3098265 server-id=3142350
level=debug ts=2019-09-23T12:50:08.793330099Z component=grpc-server msg="finished handling request"
level=debug ts=2019-09-23T12:50:32.28802285Z component=grpc-server msg="handling request" req="volume_id:\"3098265\" node_id:\"3142350\" "
level=info ts=2019-09-23T12:50:32.288189703Z component=api-volume-service msg="detaching volume from server" volume-id=3098265 server-id=3142350
level=debug ts=2019-09-23T12:50:35.147710534Z component=grpc-server msg="finished handling request"
```

</p>
</details>

<details><summary>CPU Usage over same timeframe</summary>

<p>

_Note_: CPU Usage is already slowly increasing

![grafana-csi-cpu-usage_000](https://user-images.githubusercontent.com/3393079/65427362-724df500-de12-11e9-94b9-87e730cafd0a.png)

</p></details>

**Comment by apricote** [comment]
I was able to quickly reproduce this issue in a fresh cluster using 5 cronjobs on a 1-minute schedule.

![grafana-csi-cpu-usage-2_000](https://user-images.githubusercontent.com/3393079/65530423-3c833c00-def8-11e9-811f-78a3afe12fa7.png)

<details><summary>manifest for cronjobs</summary>

```yaml
kind:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-vol-1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-job-1
  namespace: default
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: test
            image: busybox
            command: ["echo", "Hello"]
            volumeMounts:
              - mountPath: /test
                name: test
          volumes:
            - name: test
              persistentVolumeClaim:
                claimName: test-vol-1

---
kind:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-vol-2
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-job-2
  namespace: default
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: test
            image: busybox
            command: ["echo", "Hello"]
            volumeMounts:
              - mountPath: /test
                name: test
          volumes:
            - name: test
              persistentVolumeClaim:
                claimName: test-vol-2

---

kind:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-vol-3
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-job-3
  namespace: default
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: test
            image: busybox
            command: ["echo", "Hello"]
            volumeMounts:
              - mountPath: /test
                name: test
          volumes:
            - name: test
              persistentVolumeClaim:
                claimName: test-vol-3


---

kind:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-vol-4
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-job-4
  namespace: default
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: test
            image: busybox
            command: ["echo", "Hello"]
            volumeMounts:
              - mountPath: /test
                name: test
          volumes:
            - name: test
              persistentVolumeClaim:
                claimName: test-vol-4

---

kind:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-vol-5
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-job-5
  namespace: default
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: test
            image: busybox
            command: ["echo", "Hello"]
            volumeMounts:
              - mountPath: /test
                name: test
          volumes:
            - name: test
              persistentVolumeClaim:
                claimName: test-vol-5
```

</details>
