### ISSUE TITLE
Import existing volume

### ISSUE THREAD

**Issue by jorikseldeslachts** [hetznercloud/csi-driver#781]
### TL;DR

Is it possible to import an existing volume into the cluster and make it managed by the csi driver?

### Expected behavior

Reuse an already existing volume in a new cluster.

**Comment by lukasmetzner** [comment]
Hey,

this is already possible. First, you should detach your volume from any server. Afterward, you need to find out your volume ID, which you can do in the Hetzner Cloud Console, or via `hcloud volume list`. This needs to be referenced in the `volumeHandle` of your PV definition. Then you can create a PVC and reference the existing PV via `volumeName`.

I will add some documentation for this process.

``` yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: imported-data
spec:
  storageClassName: hcloud-volumes
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  csi:
    fsType: ext4
    driver: csi.hetzner.cloud
    volumeHandle: "102005585" # <-- insert volume id here

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: imported-data
spec:
  storageClassName: hcloud-volumes
  volumeName: imported-data # <-- reference your volume name here
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```
