### ISSUE TITLE
[Feature request] Logging improvement: The CSI controller could let you know if a volume can’t be attached to any node because it was created in a different location

### ISSUE THREAD

**Issue by vitobotta** [hetznercloud/csi-driver#909]
### TL;DR

Hi, today we ran into an issue where some pods couldn’t be scheduled. We checked the pod events and CSI logs, but there was no helpful information to figure out what was going on. After some digging, we realized the problem was that the volumes were created in Falkenstein, but after a big migration, all our nodes were in Nuremberg. Since the volumes and nodes were in different locations, the volumes couldn’t be attached to the new nodes. To fix we had to create new nodes in Falkenstein.

Looking back, it makes sense that volumes can’t be attached to nodes in a different physical location from where the volumes are hosted. But if the CSI logs had given us a hint about this issue, it would have saved us some time.

### Expected behavior

I think improving the logging here would be really helpful.

Thanks!

**Comment by lukasmetzner** [comment]
Hey,
the volumes should receive a `nodeAffinity` during creation. This affinity will lead to scheduling issues, that are not handled by the csi-driver. Therefore, we cannot add any logging here. The corresponding event should look something like this:
```bash
Warning  FailedScheduling  48s   default-scheduler  0/4 nodes are available: 1 node(s) had volume node affinity conflict, 3 node(s) didn't match Pod's node affinity/selector. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.
```
**example PV**
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
# [...]
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: csi.hetzner.cloud/location
          operator: In
          values:
          - fsn1
```

Could you provide more details about your setup and how you discovered the issue, in case it wasn't related to the affinities?
